### ISSUE TITLE
Title bar multiple colours at once

### ISSUE THREAD

**Issue by Djjus** [JeffreyAusborn/daoc-chat-gator-electron#1]
Green square Around the title "Chat Gator" remains even if the title bar has turned Red (inactive).

<img width="272" alt="image" src="https://github.com/JeffreyAusborn/daoc-chat-gator-electron/assets/59532170/b697f9f6-a574-43c1-bbdf-9b134602ca59">

Also the Graph button might benefit from either colours change based on its status. (red off / green on).

**Comment by autobotauz** [comment]
Stawwwwwppp :P

Fair on the log button. 
The chart button, will need to check on the transparent icon and the button itself being color changes. 

I'll call this a P4 of a P0-P4 scale. :)

**Comment by Djjus** [comment]
thats fine, thats what the tags are for

**Comment by Djjus** [comment]
resolved
